Crud Courses and states_courses
benaja-bendo/bgr-dashboard-01 pull request #33
Opened 2024-08-06 09:01 UTC by espery17

implémentatuin API Crud pour les resource des tables courses et states_courses

2024-08-06 09:01 UTC, espery17 commented
@benaja-bendo

2024-08-06 09:58 UTC, benaja-bendo requested changes
@espery17 à toi de jouer.

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Controllers/TenantControllers/CourseController.php
> +     */
Mettre à jours la documentation `spec` comme ce qui suit (pareil pour les autres méthodes de la class)

```php
#[OA\Get(
        path: '/api/v1/course',
        operationId: 'index',
        description: 'Get all courses with filter.',
        security: [['sanctum' => []]],
        tags: ['Course'],
        parameters: [
            new OA\Parameter(
                name: 'page',
                description: 'Page number.',
                in: "query",
                required: false,
                schema: new OA\Schema(type: 'integer'),
            ),
            new OA\Parameter(
                name: 'limit',
                description: 'Items per page.',
                in: "query",
                required: false,
                schema: new OA\Schema(type: 'integer'),
            ),
            new OA\Parameter(
                name: 'name',
                description: 'Name of the user.',
                in: "query",
                required: false,
                schema: new OA\Schema(type: 'string'),
            ),
            new OA\Parameter(
                name: 'email',
                description: 'Email of the user.',
                in: "query",
                required: false,
                schema: new OA\Schema(type: 'string'),
            ),
        ],
        responses: [
            new OA\Response(response: '200', description: 'Users retrieved successfully.'),
            new OA\Response(response: '401', description: 'Unauthorized.'),
            new OA\Response(response: '404', description: 'Not found.'),
        ],
    )]

```

une issues viendra pour les filtres.

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Controllers/TenantControllers/CourseController.php
> +class CourseController extends ApiController
remplacé `class CourseController extends ApiController` par `class CourseController extends Controller`

Le fichier ApiController.php sera supprimer plus tard (pas utile)

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Controllers/TenantControllers/CourseController.php
> +            'slug' => 'required|string|max:255',
Supprimer la key `slug`
---

la key `slug` ici n'est pas nécessaire  dans la validation. Elle sera généré à partir de la key `name`.

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Controllers/TenantControllers/CourseController.php
> +    public function show($id): JsonResponse
Typé le paramètre de fonction  -> `String $id`

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Controllers/TenantControllers/CourseController.php
> +
Mettre à jour par :
```php
if (!$course) {
            return $this->errorResponse(
                error: 'Course not found.',
                code: 404
            );
        }

```

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Controllers/TenantControllers/CourseController.php
> +    public function update(Request $request, $id): JsonResponse
typé les paramètres de méthodes ->
`public function update(Request $request,String $id): JsonResponse`

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Controllers/TenantControllers/CourseController.php
> +            'slug' => 'required|string|max:255',
Pareil la key `slug` doit être auto généré par le key name.
-> supprimé la key `slug`

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Controllers/TenantControllers/CourseController.php
> +    }
ici tu devrais avoir un fichier CourseCollection pour faire un `new CourseCollection($courses)` c'est mieux.

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Controllers/TenantControllers/CourseController.php
> +    public function destroy($id): JsonResponse
typé avec `String $id`

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Controllers/TenantControllers/CourseController.php
> +            return $this->errorResponse('Course not found', [], 404);
retirer  `[]`

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Controllers/TenantControllers/StateCourseController.php
> +     */
Mettre à jours la doc spec OpenApi sur l'ensemble des méthodes de la class.

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Controllers/TenantControllers/StateCourseController.php
> +class StateCourseController extends ApiController
remplacer `ApiController` par `Controller`

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Controllers/TenantControllers/StateCourseController.php
> +            'name' => 'required|string|max:255',
1. `max:255` trop grand -> partir sur `max:100` 
2. Mettre un `min:3`

Ouvert à la discussion.

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Resources/CourseResource.php
Top 👍🏽

2024-08-06 09:58 UTC, benaja-bendo commented on app/Http/Resources/StateCourseResource.php
top 👍🏽

2024-08-06 09:58 UTC, benaja-bendo commented on app/Models/StateCourse.php
> +    protected $guarded = [];
partir sur `$fillable` c'est mieux pour limiter les entrées à la base de donnée.

2024-08-06 09:58 UTC, benaja-bendo commented on app/Models/StateCourse.php
> +    public function courses()
c'est un détail mais typé le retour c'est important `: HasMany`

2024-08-06 09:58 UTC, benaja-bendo commented on app/Models/Course.php
> +    protected $guarded = [];
partir sur `$fillable` c'est mieux pour limiter les entrées à la base de donnée.

2024-08-06 09:58 UTC, benaja-bendo commented on app/Models/Course.php
> +    public function stateCourse()
c'est un détail mais typé le retour c'est important `: BelongsTo`

2024-08-13 22:24 UTC, espery17 commented on app/Http/Controllers/TenantControllers/CourseController.php
> +            'slug' => 'required|string|max:255',
**c'est fais !**

2024-08-13 22:25 UTC, espery17 commented on app/Http/Controllers/TenantControllers/CourseController.php
> +    public function show($id): JsonResponse
**c'est fais !**

2024-08-17 16:11 UTC, benaja-bendo approved these changes

2024-08-17 16:12 UTC, benaja-bendo commented
👍🏽 mise à jour de la doc

![image](https://github.com/user-attachments/assets/74dde858-f51d-4404-b197-84280c001631)

2024-08-17 16:12 UTC, merged